### ISSUE TITLE
Release binaries for older machines

### ISSUE THREAD

**Issue by pepa65** [shiro/map2#1]
Looks very interesting, but it suffers from the common "requires a very recent GLIBC" issue. If you could release binaries that are made on an older machine, it would not affect people with a newer GLIBC, but it would extend your reach. I am on the latest Ubuntu-family LTS (20.04), but last month I was still running 18.04 and I ran into this issue a lot...
Debug output:
```
map2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by map2)
map2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by map2)
```

**Comment by pepa65** [comment]
Do you have any pointers how I could build from source? Or do you think upgrading my rust version would help??

**Comment by shiro** [comment]
You should be able to build it as described by the README. The latest stable version of rust should compile it with no issues.
If you have any issues compiling just let me know.
