### ISSUE TITLE
[ Question ] Is it possible to emulate controllers?

### ISSUE THREAD

**Issue by RAVENz46** [shiro/map2#14]
Is it possible to emulate any controller with mouse and keyboard?

**Comment by shiro** [comment]
I tried this out and fixed some related bugs in the process :D

You can check out the [example](https://shiro.github.io/map2/en/examples/keyboard_to_controller/) in the docs for more details. Some of the capabilities API is not fully documented yet but will (probably) not change.

The example doesn't use a mouse, but it's also possible (exercise for the reader).

Also make sure you're on at least `map2 2.0.8` to make it work as expected.

**Comment by RAVENz46** [comment]
@shiro Thanks for providing an example! I will try it.
