### ISSUE TITLE
Getting UNSUPPORTED_PLATFORM error in X11

### ISSUE THREAD

**Issue by hbertoduarte** [shiro/map2#15]
I was testing the window change events on my machine (a fairly standard Arch setup) but, for some reason, I encountered the UNSUPPORTED_PLATFORM error. Upon further investigation, I got to this line:
https://github.com/shiro/map2/blob/0c1e78a82fbe36b76d380ccc2f15ba35f9e94821/src/platform/mod.rs#L32
Testing the same code in Rust I found that, in my machine, `info.stdout` ends up as `"x11\n"`, and that messes up the test.

**Comment by shiro** [comment]
Thanks for debugging, I'll add a patch on monday that removes `\n` I guess ^^

**Comment by shiro** [comment]
Should be fixed in `2.0.13`.
