### ISSUE TITLE
I can't figure out where this code is failing.

### ISSUE THREAD

**Issue by HarmonBlues** [shiro/map2#5]
// =================
// APASTRON KEYBINDS
// =================
sleep(2000); // sleep 2s
print("the active window class is: " + active_window_class());
// Main File
on_window_change(||{
	if(active_window_class() == "steam_app_1264850"){
		print("Apastron mappings loaded: " + active_window_class());
		// maps 'esdf' to 'wasd'
		e::w;
		s::a;
		d::s;
		f::d;
                c::KEY_CAPSLOCK;
		v::BTN_THUMB;
		BTN_1::z;
		BTN_2::BTN_BACK;
		BTN_3::BTN_FORWARD;
		a::KEY_LEFTSHIFT;
		g::b;
	}else{
		print("Apastron mappings reverted: " + active_window_class());
		// maps 'esdf' back to 'esdf'
		e::e;
		s::s;
		d::d;
		f::f;
        c::c;
		v::v;
		BTN_1::BTN_1;
		BTN_2::BTN_2;
		BTN_3::BTN_3;        
		a::a;
		g::g;
    }else if({send_modifier("{shift end}")}){
        print("exiting apastron.m2 ");
        execute("exit(0)");
         }
	});

**Comment by HarmonBlues** [comment]
I think i've done something weird with either the keymappings or the else if stuff.

**Comment by HarmonBlues** [comment]
// =================
// APASTRON KEYBINDS
// =================
+home::{
print("the active window class is: " + active_window_class());
    };

+end::{
    print("exiting apastron.m2 ");
    execute("exit(0)");
    };

// Main File
on_window_change(||{
	if(active_window_class() == "steam_app_1264850"){
		print("Apastron mappings loaded: " + active_window_class());
		// maps 'esdf' to 'wasd'
		e::w;
		s::a;
		d::s;
		f::d;
        c::capslock;
		v::BTN_EXTRA;
		BTN_1::z;
		BTN_2::BTN_BACK;
		BTN_3::BTN_FORWARD;
		a::KEY_LEFTSHIFT;
		g::b;
        t::e;

	}else{
		print("Apastron mappings reverted: " + active_window_class());
		// maps 'esdf' back to 'esdf'
		e::e;
		s::s;
		d::d;
		f::f;
        c::c;
		v::v;
		BTN_1::BTN_1;
		BTN_2::BTN_2;
		BTN_3::BTN_3;        
		a::a;
		g::g;
		t::t;
        
	}
	});

**Comment by shiro** [comment]
- doing `if(...){...}else{...}else if(...){...}` completely ignores the last branch since `else` catches everything not caught by `if`, this should throw an error and is considered a bug in my parser.
- does binding `c::capslock` (without anything else, just this line in a new `m2` file) work for you?
- script looks fine otherwise and should work, please let me know what exactly does and does not work

**Comment by HarmonBlues** [comment]
>     * doing `if(...){...}else{...}else if(...){...}` completely ignores the last branch since `else` catches everything not caught by `if`, this should throw an error and is considered a bug in my parser.
> 
>     * does binding `c::capslock` (without anything else, just this line in a new `m2` file) work for you?
> 
>     * script looks fine otherwise and should work, please let me know what exactly does and does not work

Well `c::capslock' did not work in its own file.
Otherwise i'm unsure what the bind should be on the third thumb button for the Logitech G02 Proteus Core. I've tried extra, thumb and side.

**Comment by shiro** [comment]
Hmm, `c::capslock` works fine for me, please make sure other bindings (i.e. `a::b`) work and that you have all device file descriptors in the `devices.list` file. If it's just this key I'd be interested in a log of evdev events the file descriptor is emitting.

To find out which event the mouse is sending you first need to find out which file descriptor the mouse is sending through and then log the evdev events (this can be done on the terminal without much effort, google can help).

Currently only key mappings are supported, but pointer events are planned for a future release. Your friend might find an existing evdev remapping script that inverts axes assuming someone wrote and published it.

**Comment by HarmonBlues** [comment]
I figured out that i had some of the mappings backwards. I needed `capslock::c` for example. 

I still can't figure out what this third mouse button maps to in:
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

**Comment by HarmonBlues** [comment]
```
// =================
// APASTRON KEYBINDS
// =================
+home::{
print("the active window class is: " + active_window_class());
    };

+end::{
    print("exiting apastron.m2 ");
    execute("exit(0)");
    };

// Main File
on_window_change(||{
	if(active_window_class() == "steam_app_1264850"){
		print("Apastron mappings loaded: " + active_window_class());
		// remapping keys
		e::w;
		s::a;
		d::s;
		f::d;
		capslock::c;
		z::key_1;
		btn_side::key_2;
		btn_extra::key_3;
		btn_forward::v;
		a::leftshift;
		g::b;
	        t::e;
		btn_left::"{e}{btn_left}";          
          
	}else{
		print("Apastron mappings reverted: " + active_window_class());
		// reverting keys
		e::e;
		s::s;
		d::d;
		f::f;
                capslock::capslock;
                z::z;
                btn_side::btn_side;
                btn_extra::btn_extra;
                btn_forward::btn_forward;
                a::a;  
                g::g;
                t::t;
                btn_left::btn_left;
        
	}
	});
// End of File
```

**Comment by shiro** [comment]
- mappings are not recursive, even if you bind ` e::w`, any mapping *to* `e` will still output `e` rather than `w`.
- binding a click action to sequences results in binding the `down` state and stubbing the `repeat` and `up` state, meaning you can only trigger it once per key-press. This is by design, since binding repeat is probably not what most people want.

I'll release an update once I'm done testing it and will figure out how to solve your "full auto" use-case and reply to you after that.

**Comment by HarmonBlues** [comment]
> I'll release an update once I'm done testing it and will figure out how to solve your "full auto" use-case and reply to you after that.
That would be amazing! Thank you :D

**Comment by HarmonBlues** [comment]
Shiro, have you had any time to test things out?

**Comment by shiro** [comment]
Sorry but I'm busy with work and have no time to finish up the python update. I'll ping you once its up.
If it's very urgent feel free to submit a patch. Currently it seems that mapping to `[key] repeat` doesn't work (throws a parse error), so the parser needs to be fixed. Once that is done you could map `[key] down`, `[key] up` and `[key] repeat` individually to achieve what you need.

**Comment by HarmonBlues** [comment]
That's understandable. Sounds good.

**Comment by shiro** [comment]
Sorry for the delay, the new [python branch](https://github.com/shiro/map2/discussions/9) is now up for preview (things might break, there is almost no docs, etc.), however I did fix the bug mentioned before.  
You can now map to keys' `repeat` state to output events when the key is pressed for some time:
```.py
import map2

reader = map2.Reader(patterns=[
    "/dev/input/by-path/pci-0000:03:00.0-usb-0:9:1.0-event-kbd",
])
writer = map2.Writer(reader)

writer.map("pagedown", lambda: map2.exit())

writer.map_key("{a down}", "b")
writer.map_key("{a repeat}", "c")
writer.map_key("{a up}", "d")

map2.wait()
```
Hope this helps :)

**Comment by HarmonBlues** [comment]
How goes things shiro?

**Comment by shiro** [comment]
I'm personally using the python branch on my machine and the above should work fine there.

There are some issues that I'll get around to fixing and finalizing the API, writing docs and making it the main branch, I'll send another reply when I find some time to do it.

If you need this working today, you can either try out the python branch or make a PR on the legacy repo with the backported fix (it's a somewhat easy fix).

**Comment by HarmonBlues** [comment]
oh, i meant like how are things with you? XD

**Comment by shiro** [comment]
Can't complain, working on lots of interesting technical challenges, going outside, touching grass and such :D

**Comment by HarmonBlues** [comment]
So i'm heading back to using map2 again. I am unsure why my output is giving me a device or resource busy error 16 message.

**Comment by HarmonBlues** [comment]
Sorry to be a bother, but if you do have a sec to explain what i've done wrong or what i can fix i'd be really appreciative.

**Comment by shiro** [comment]
I don't really know what your particular issue is and there's no straightforward result on google.

- try to run it on legacy map2 (not python), does it work there?
- try to map only one device at a time, just log some message and see if that works
- try another device, see if that works
- run it without a graphical env. in a TTY, does that work?

Something else on your particular system is probably locking the device, so you might want to check if something is running in the background, try to run it without a desktop environment, etc.

This are just some pointers to test what works and help you figure it out, I can't really give you tech support though, hope you manage to figure it out. If you find a bug with map2 you can report it of course.

**Comment by HarmonBlues** [comment]
No thank you. Those ideas are helpful and I'll give them a try.

**Comment by HarmonBlues** [comment]
I believe I've found the correct device now. But I'm getting no output from my keyboard inputs after launching a script with map2.

**Comment by shiro** [comment]
There's now an official release of version 2, which does a lot of things differently.

If you're still having issues, you might want to check out the new [documentation](https://shiro.github.io/map2/en/basics/getting-started/), which goes in-depth on how to configure things.
